Login_App/urls.py
from django.conf.urls import url
from django.urls import path
from .views.signup_view import Sign_up
from .views.login_view import Login_user, edit_profile, logout_user, userprofile

app_name = "Login_App"

urlpatterns = [
    path('signup/', Sign_up.as_view(), name='signup'),
    path('login/', Login_user.as_view(), name='login'),
    path('edit/', edit_profile, name='edit'),
    path('logout/', logout_user, name='logout'),
    path('profile/', userprofile, name='userprofile'),

]

Photo_Sharing_WebApp/urls.py
from django.contrib import admin
from django.urls import path , include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from Posts_App import views
from Posts_App.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('post/', include('Posts_App.urls')),
    path('', Home.as_view(), name = 'home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posts_App/urls.py
from Posts_App import views
from django.urls import path
from .views import Home

app_name= 'Posts_App'

urlpatterns = [
    path('', Home.as_view(), name = 'home'),
    path('album/', views.album_show, name='album_show'),
    path('add_album/', views.add_album, name='add_album'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/',views.unliked, name='unliked'),
]

Login_App/models.py
from django.db import models
from django.urls import reverse
# To Create a Custom User Model and Admin Panel

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy

# To automatically create one to one objects

from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class MyUserManager(BaseUserManager):
    """ A custom Manager to deal with emails as unique identifer """

    def _create_user(self, email, password, **extra_fields):
        """ Creates and saves a user with a given email and password"""

        if not email:
            raise ValueError("The Email must be set!")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        ugettext_lazy('staff status'),
        default=False,
        help_text=ugettext_lazy('Designates whether the user can log in this site')
    )

    is_active = models.BooleanField(
        ugettext_lazy('active'),
        default=True,
        help_text=ugettext_lazy(
            'Designates whether this user should be treated as active. Unselect this instead of deleting accounts')
    )

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=264, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def __str__(self):
        return self.username + "'s Profile"

    def is_fully_filled(self):
        fields_names = [f.name for f in self._meta.get_fields()]

        for field_name in fields_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

Login_App/forms.py
from django.forms import ModelForm
from Login_App.models import User, Profile

from django.contrib.auth.forms import UserCreationForm


# forms
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class EditProfile(ModelForm):
    class Meta:
        model = Profile()
        exclude = ('user',)

Login_App/views/login_view.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse

from Login_App.forms import EditProfile
from Login_App.models import Profile, User
from Posts_App.forms import PostForm
from Posts_App.models import Photo, Album, Post

# Authetication
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout

from django.contrib.auth.decorators import login_required
# Messages
from django.views import View


# Create your views here.
class Login_user(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'Login_App/login.html', context={'form': form})

    def post(self, request):
        if request.method == 'POST':
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('Posts_App:home'))
        return render(request, 'Login_App/login.html', context={'form': form})


@login_required
def edit_profile(request):
    current_user = Profile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('Login_App:userprofile'))
    return render(request, 'Login_App/edit_profile.html', context={'form': form, 'title': 'Edit Profile . Social'})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('Posts_App:home'))


def userprofile(request):
    form = PostForm()
    user = request.user
    album = request.GET.get('album')
    if album == None:
        photos = Photo.objects.filter(album__user=user)
    else:
        photos = Photo.objects.filter(
            album__album_name=album, album__user=user)

    photos.save(user=user)
    album_list = Album.objects.filter(user=user)
    album_list.save(user=user)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = Post.objects.private_post()
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'Login_App/user.html',
                  context={'form': form, 'album_list': album_list, 'photos': photos})

Login_App/views/signup_view.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from Login_App.forms import SignUpForm
# Messages
from django.views import View


# Create your views here.
class Sign_up(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'Login_App/signup.html', context={'form': form})

    def post(self, request):
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('Login_App:login'))
        return render(request, 'Login_App/signup.html', context={'title': 'Sign up . Social', 'form': form})

templates/Login_App/edit_profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{%block title_block%}Edit Profile{%endblock%}
{% block body_block %}
<div class="container mt-5 col-sm-7 border rounded" style="background-color: #ffffff;">
    <h3 class="alert alert-light border rounded mt-4 mb-4 rounded " align="center"><b>Edit Your Profile</b></h3>
    <form method="POST" enctype="multipart/form-data">
        {{form|crispy}}
        {% csrf_token %}
        <div class="text-center">
            <button type="submit" name="button" class='btn btn-primary btn-lg col-lg-4'>Submit</button>
        </div>
        <br>
        <hr>
        <br>
    </form>
</div>
<br>
<br>
{% endblock %}

templates/Login_App/login.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
<div class="container border rounded mt-5 col-sm-6">
    <h3 class="alert alert-light border rounded mt-4 mb-4 rounded" align="center"><b>Login Here</b></h3>
    <form action="{% url 'Login_App:login' %}" method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <br>
        <div class="text-center">
            <button type="submit" class="btn btn-secondary btn-lg col-lg-4" href="#">Login</button>
        </div>
    </form>
    <br>
    <p>Doesn't have an account? <a href="{% url 'Login_App:signup' %}">Create New Account</a></p>
</div>
{% endblock %}

templates/Login_App/signup.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} signup {% endblock %}
{% block body_block %}
<div class="container border rounded mt-5 col-sm-6">
    <h3 class="alert alert-light border rounded mt-4 mb-4 rounded" align="center"><b>Sign up
    </b></h3>
    <form action="{% url 'Login_App:signup' %}" method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <br>
        <div class="text-center">
            <button type="submit" class="btn btn-secondary btn-lg col-lg-4">Sign-up</button>
        </div>
    </form>
    <br>
    <p>Already have an account? <a href="{% url 'Login_App:login' %}">Login Here</a></p>
</div>
<br>
{% endblock %}

templates/Login_App/user.html
{% extends 'navbar.html' %}
{% block title_block %} Profile {% endblock %}
{% block css_block %}
<style>

  .crop {
    height: 50%;
    width : 50%;
    object-fit: cover;
  }
  .pic img {
    border-radius: 50%!important;
    margin-left: 75px;
    margin-top: -90px;
}
.btn-outline-info {
    color: #82B6D9;
    border-color: #82B6D9;

    }
    .image-thumbail {
        height: 200px;
        object-fit: cover;
    }

    .list-group-item a {
        text-decoration: none;
        color: black;
    }

</style>
{% endblock %}

{% block body_block %}

<div class="w3-sidebar w3-bar-block w3-card " style="width:25%; left:8%" id="leftMenu">
    <div style="background-color: #82B6D9; height: 100px;">
    </div>
    <div class="pic" style="background-color: #ffffff;">
        {% if user.profile.profile_pic %}
        <img src="/media/{{user.profile.profile_pic}}" width="160px" height="160px" class=" rounded-circle">
        {% else %}
        <img src="/media/default.jpg" width="160px" height="160px" class="rounded-circle">
        {% endif %}
        <br>
    </div>
    <div style="background-color: #ffffff; padding: 15px;">
        <h3>{{user.profile.username}}</h3>
        <hr style="color:#82B6D9;">
        <h5><i class="fas fa-edit"></i>&nbsp; &nbsp;{{user.post.count}}Posts &nbsp; &nbsp; &nbsp;<a
                href="{% url 'Login_App:edit' %}" class="btn btn-outline-info"><b>Edit Profile</b></a></h5>
        <hr style="color:#82B6D9;">
        <h4>{{user.profile.full_name}}</h4>
        <p>{{user.profile.description|linebreaks}}</p>
    </div>
    <br><br> <br>

</div>

<div class="w3-sidebar w3-bar-block w3-card" style="width:15%; right:8%;" id="rightMenu">
    <div class="card" style="padding: 10px;">
        <div class="card-header">
            Album List
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a href="{% url 'Login_App:userprofile' %}">All</a>
            </li>
            {% for album in album_list %}
            <li class=" list-group-item">
                <a href="{% url 'Login_App:userprofile' %}?album={{album.album_name}}">
                    {{album.album_name}}
                </a>
            </li>
            {% endfor %}
            <a href="{% url 'Posts_App:add_album' %}" class="btn btn-dark btn-block btn-sm m-1">Add Photo</a>
        </ul>
    </div>
</div>
<div class="w3-container" style="margin-left:29%; margin-right:4%;">
    <div class="w3-container" style="width:80%">

        <div class="row" style="height: 50px;">
            <div style="background-color: #82B6D9; height: 10px;">
            </div>
            <div style="height: 55px; background-color: #ffffff;">
                <div class="d-flex bd-highlight">
                    <div class="flex-grow-1 bd-highlight">
                        {% if user.profile.profile_pic %}
                        <a class="nav-link" href="{% url 'Login_App:userprofile' %}"><img
                                src="/media/{{user.profile.profile_pic}}" width="40px" height="40px"
                                class="rounded-circle"></a>
                        {% else %}
                        <a class="nav-link" href="{% url 'Login_App:userprofile' %}"><img src="/media/default.jpg"
                                                                                          width="40px" height="40px"
                                                                                          class="rounded-circle"></a>
                        {% endif %}
                    </div>
                    <div class="p-2 bd-highlight">
                        <button type="button" class="btn btn-outline-secondary" data-toggle="modal"
                                data-target="#myModal">
                            Post a Photo
                        </button>
                    </div>
                    <div class="p-2 bd-highlight">
                        <a href="{% url 'Posts_App:add_album' %}" class="btn btn" style="background-color: #82B6D9;">Create
                            Album</a>
                    </div>
                </div>
            </div>
        </div>


        <!-- The Modal -->
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Post a Photo</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        <form method="POST" enctype="multipart/form-data">
                            {{form.as_p}}
                            {% csrf_token %}
                            <button type="submit">Post</button>
                        </form>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>
        <br>
        <!-------------------------------------------album------------------------->
        <div class="row" style="background-color: #ffffff; ">
            <br>
            <div>
                <h4 class="text-center"><b>Album Photos</b></h4>
                <hr>
            </div>
            {% for photo in photos %}
            <div class="col-md-4">
                <div class="card my-2">
                    <img class="image-thumbail" src="/media/{{photo.image}}" alt="Card image cap">
                    <div class="card-body">
                        <small>Album: {{photo.album.album_name}}</small>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <hr>
        <div class="post_photo">
            {% for post in user.post.all %}
            <div class="border rounded " style="background-color: #ffffff;">
                <div style="margin-left: 10px;">
                    {% if post.author.profile.profile_pic %}
                    <img src="/media/{{post.author.profile.profile_pic}}" width="40px" height="40px"
                         style="margin-top: 15px;" class="rounded-circle">
                    {% else %}
                    <img src="/media/default.jpg" width="40px" height="40px" class="rounded-circle">
                    {% endif %}
                    <a>&nbsp;{{post.author.profile.username}}</a>
                    <a>&nbsp;&nbsp;<i class="fas fa-clock" style="color:#82B6D9;"></i>&nbsp;{{post.upload_date}}</a>
                </div>
                <hr>
                <div class="post_caption" style="margin-left: 10px; margin-bottom: 10px;">
                    {{post.caption}}
                </div>
                <br>
                <img class="crop mx-auto d-block" src="/media/{{post.image}}">
                <br>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>

{%endblock%}