Login_App/urls.py
from django.conf.urls import url
from django.urls import path
from .views.signup_view import Sign_up
from .views.login_view import Login_user, edit_profile, logout_user, userprofile

app_name = "Login_App"

urlpatterns = [
    path('signup/', Sign_up.as_view(), name='signup'),
    path('login/', Login_user.as_view(), name='login'),
    path('edit/', edit_profile, name='edit'),
    path('logout/', logout_user, name='logout'),
    path('profile/', userprofile, name='userprofile'),

]

Photo_Sharing_WebApp/urls.py
from django.contrib import admin
from django.urls import path , include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from Posts_App import views
from Posts_App.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('post/', include('Posts_App.urls')),
    path('', Home.as_view(), name = 'home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posts_App/urls.py
from Posts_App import views
from django.urls import path
from .views import Home

app_name= 'Posts_App'

urlpatterns = [
    path('', Home.as_view(), name = 'home'),
    path('album/', views.album_show, name='album_show'),
    path('add_album/', views.add_album, name='add_album'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/',views.unliked, name='unliked'),
]

Posts_App/models.py
from django.db import models
from Login_App.models import User
from django.utils import timezone


# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(
            PostManager,
            self).filter(draft=False).filter(publish__lte=timezone.now())

    def public_post(self, *args, **kwargs):
        return super(
            PostManager,
            self).filter(public=True)

    def private_post(self, *args, **kwargs):
        return super(
            PostManager,
            self).filter(public=False)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    public = models.BooleanField(default=False)
    private = models.BooleanField(default=True)

    objects = PostManager()

    @property
    def is_public(self):
        return self.public

    @property
    def is_private(self):
        return self.private

    class Meta:
        ordering = ['-upload_date', ]


class Album(models.Model):
    class Meta:
        verbose_name = 'Album'
        verbose_name_plural = 'Album_list'
        ordering = ['-upload_date', ]

    album_author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='album_aut')
    album_name = models.CharField(max_length=100, null=False, blank=False)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.album_name


class Photo(models.Model):
    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'
        ordering = ['-upload_date', ]

    photo_aut = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='photo_aut')
    album = models.ForeignKey(Album, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to='album_pic', blank=True)
    a_caption = models.TextField(max_length=264, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.a_caption


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

Posts_App/forms.py
from django import forms
from Posts_App.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['image', 'caption', 'private', 'public']

Posts_App/views.py
from django.shortcuts import HttpResponse, HttpResponseRedirect, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from Login_App.models import Profile, User

from Posts_App.models import Post, Like, Album, Photo
from django.views import View

from django.views.generic import DetailView


# Create your views here.
class Home(View):
    def get(self, request):
        user = request.user
        posts = Post.objects.filter(public=True)
        album_list = Album.objects.all
        photos = Photo.objects.all
        return render(request, 'Posts_App/home.html',
                      context={'posts': posts, 'album_list': album_list, 'photos': photos})


@login_required
def add_album(request):
    user = request.user
    album_list = user.album_set.all()
    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')
        if data['album_new'] != '':
            album, created = Album.objects.get_or_create(
                user=user,
                album_name=data['album_new'])
        else:
            album = None

        for image in images:
            photo = Photo.objects.create(
                album=album,
                a_caption=data['a_caption'],
                image=image,
            )
        return redirect('Login_App:userprofile')

    context = {'album_list': album_list}
    return render(request, 'Posts_App/add_album.html', context)

@login_required
def album_show(request):
    photos = Photo.objects.all()
    album_list = Album.objects.all()
    context = {'album_list': album_list, 'photos': photos}
    return render(request, 'Posts_App/album_home.html', context)


@login_required
def liked(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    if not already_liked:
        liked_post = Like(post=post, user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('home'))


@login_required
def unliked(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('home'))

templates/Posts_App/add_album.html
{% extends 'navbar.html' %}
{% block title_block %}Create Album{% endblock %}

{% block body_block %}
<body class="m-5">
<div class="row justify-content-center">
    <div class="col-md-4">
        <a href="{% url 'Login_App:userprofile' %}" class="btn btn-dark my-3">Go Back</a>
        <div class="card">

            <form method='POST' action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group m-3">
                    <label>Caption</label>
                    <input required name="a_caption" type="text" placeholder="Enter a caption"
                           class="form-control">
                </div>

                <div class="form-group m-3">
                    <label>Select a Album</label>
                    <select name="album_list" class="form-control">
                        <option value='none'>Select a album...</option>
                        {% for album in album_list %}
                        <option value='{{album.id}}'>{{album.album_name}}</option>
                        {% endfor %}
                    </select>
                </div>


                <div class="form-group m-3">
                    <label>Create a new Album</label>
                    <input name="album_new" type="text" placeholder="Create a new category"
                           class="form-control">
                </div>

                <div class="form-group m-3">
                    <label>Upload image</label>
                    <input required name="images" type="file" multiple class="form-control-file">
                </div>

                <button type='submit' class="btn btn-primary m-3">Submit</button>

            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/Posts_App/album_home.html
{% extends 'navbar.html' %}
{% block title_block %} All Album {% endblock %}

{% block body_block %}
<style>
   .image-thumbail {
        height: 200px;
        object-fit: cover;
    }
    .list-group-item a {
        text-decoration: none;
        color: black;
    }


</style>
<div class="w3-sidebar w3-bar-block w3-card" style="width:22%; right:13%; background-color:#F2F2F2;" id="rightMenu">
    <div class="row">
        <hr>
        <div class="col-sm-4">
            {% if user.profile.profile_pic %}
            <img src="/media/{{user.profile.profile_pic}}" width="50px" height="50px" style="margin-left:15%"
                 class="rounded-circle">
            {% else %}
            <img src="/media/default.jpg" width="50px" height="50px" style="margin-left:15%" class="rounded-circle">
            {% endif %}
        </div>
        {{user.profile.username}}
        <br>
        {{user.profile.full_name}}
    </div>
    <hr>
    <div class="card" style="padding: 10px;">
        <div class="card-header text-center">
            Album List
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a href="{% url 'Posts_App:album_show' %}">All</a>
            </li>
            {% for album in album_list %}
            <li class=" list-group-item">
                <a href="{% url 'Login_App:userprofile' %}?album={{album.album_name}}">
                    {{album.album_name}}  &nbsp;<a style="color:#82B6D9;">Created by :&nbsp; {{album.user.profile.username}}</a>
                </a>
            </li>
            {% endfor %}
            <a href="{% url 'Posts_App:add_album' %}" class="btn btn-dark btn-block btn-sm m-1">Add Photo</a>
        </ul>
        <br><br><br><br><br>
    </div>
</div>


<div class="w3-container" style="margin-left:13%; margin-right:13%; width:50%;">
    {% if search %}
    {% for user in result %}
    <div class="row">
        <div class="col-sm-2">
            {% if user.profile.profile_pic %}
            <img src="/media/{{user.profile.profile_pic}}" width="75px" height="75px" class="rounded-circle">
            {% else %}
            <img src="/media/default.jpg" width="75px" height="75px" class="rounded-circle">
            {% endif %}
        </div>
        <div class="col-sm-10">
            <a href="{% url 'Login_App:user' username=user.username %}">{{user.profile.username}}</a>
            <br>
            {{user.full_name}}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="row" style="height: 50px;">
        <div style="background-color: #82B6D9; height: 10px;">
        </div>
        <div style="height: 55px; background-color: #ffffff;">
            <div class="d-flex bd-highlight">
                <div class="p-2 bd-highlight">
                    <a href="{% url 'Posts_App:home' %}" class="btn btn-outline-secondary">View Single Photos</a>
                </div>
                <div class="p-2 bd-highlight">
                    <a href="{% url 'Posts_App:album_show' %}" class="btn btn" style="background-color: #82B6D9;">View
                        Album Photos</a>
                </div>
            </div>
        </div>
    </div>
    <br>
    <!-------------------------------------------album------------------------->


    <div class="row" style="background-color: #ffffff;">
        <hr style="color: #ffffff">
        {% for photo in photos %}
        <div class="col-md-4">
            <div class="card my-2">
                <img class="image-thumbail" src="/media/{{photo.image}}" alt="Card image cap">
                <div class="card-body">
                    <small>Album: {{photo.album.album_name}}</small>
                </div>
            </div>
        </div>
        {% endfor %}
        <hr>
    </div>
    <br>
    {% endif %}
</div>
{% endblock %}

templates/Posts_App/home.html
{% extends 'navbar.html' %}
{% block title_block %} Home {% endblock %}

{% block body_block %}
<style>
   .image-thumbail {
        height: 200px;
        object-fit: cover;
    }
    .list-group-item a {
        text-decoration: none;
        color: black;
    }

</style>
<div class="w3-sidebar w3-bar-block w3-card" style="width:22%; right:13%; background-color:#F2F2F2;" id="rightMenu">
    <div class="row">
        <hr>
        <div class="col-sm-4">
            {% if user.profile.profile_pic %}
            <img src="/media/{{user.profile.profile_pic}}" width="50px" height="50px" style="margin-left:15%"
                 class="rounded-circle">
            {% else %}
            <img src="/media/default.jpg" width="50px" height="50px" style="margin-left:15%" class="rounded-circle">
            {% endif %}
        </div>
        {{user.profile.username}}
        <br>
        {{user.profile.full_name}}
    </div>
    <hr>
</div>


<div class="w3-container" style="margin-left:13%; margin-right:13%; width:50%;">
    {% if search %}
    {% for user in result %}
    <div class="row">
        <div class="col-sm-2">
            {% if user.profile.profile_pic %}
            <img src="/media/{{user.profile.profile_pic}}" width="75px" height="75px" class="rounded-circle">
            {% else %}
            <img src="/media/default.jpg" width="75px" height="75px" class="rounded-circle">
            {% endif %}
        </div>
        <div class="col-sm-10">
            <a href="{% url 'Login_App:user' username=user.username %}">{{user.profile.username}}</a>
            <br>
            {{user.full_name}}
        </div>
    </div>
    {% endfor %}
    {% else %}

    <div class="row" style="height: 50px;">
        <div style="background-color: #82B6D9; height: 10px;">
        </div>
        <div style="height: 55px; background-color: #ffffff;">
            <div class="d-flex bd-highlight">
                <div class="p-2 bd-highlight">
                    <a href="{% url 'Posts_App:home' %}" class="btn btn-outline-secondary">View Single Photos</a>
                </div>
                <div class="p-2 bd-highlight">
                    <a href="{% url 'Posts_App:album_show' %}" class="btn btn" style="background-color: #82B6D9;">View
                        Album Photos</a>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        {% for post in posts %}
        <div style=" background-color: #ffffff;">
            <div style="padding:10px">
                {% if post.author.profile.profile_pic %}
                <img src="/media/{{post.author.profile.profile_pic}}" width="40px" height="40px" class="rounded-circle">
                {% else %}
                <img src="/media/default.jpg" width="40px" height="40px" class="rounded-circle">
                {% endif %}
                <a href="{% url 'Login_App:userprofile' %}">{{post.author.profile.username}}</a>
            </div>
            <div class="post_caption" style="margin-left: 10px; margin-bottom: 10px;">
                {{post.caption}}
            </div>
            <img src='/media/{{post.image}}' width="100%">
            <div style="padding:20px">
                {{ post.liked_post.count }} Likes <br>
                {% if post.pk in liked_post_list %}
                <a href="{% url 'Posts_App:unliked' pk=post.pk %}"><i class="far fa-heart"
                                                                      style="font-size:36px"></i></a>
                {% else %}
                <a href="{% url 'Posts_App:liked' pk=post.pk %}"><i class="fas fa-heart" style="font-size:36px"></i></a>
                {% endif %}
            </div>
        </div>
        <hr style="color : #ffffff;">
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}