Login_App/urls.py
from django.conf.urls import url
from django.urls import path
from .views.signup_view import Sign_up
from .views.login_view import Login_user, edit_profile, logout_user, userprofile

app_name = "Login_App"

urlpatterns = [
    path('signup/', Sign_up.as_view(), name='signup'),
    path('login/', Login_user.as_view(), name='login'),
    path('edit/', edit_profile, name='edit'),
    path('logout/', logout_user, name='logout'),
    path('profile/', userprofile, name='userprofile'),

]

Photo_Sharing_WebApp/urls.py
from django.contrib import admin
from django.urls import path , include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from Posts_App import views
from Posts_App.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('post/', include('Posts_App.urls')),
    path('', Home.as_view(), name = 'home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posts_App/urls.py
from Posts_App import views
from django.urls import path
from .views import Home

app_name= 'Posts_App'

urlpatterns = [
    path('', Home.as_view(), name = 'home'),
    path('album/', views.album_show, name='album_show'),
    path('add_album/', views.add_album, name='add_album'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/',views.unliked, name='unliked'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <title>{% block title_block %} Social {% endblock %}</title>

</head>
<body>

<div class="container" style='padding-top:20px'>
    {% block body_block %} {% endblock %}

</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


    <title>{% block title_block %} Social {% endblock %}</title>

    {% block css_block %}
    {% endblock %}

</head>
<body style="background-color: #F2F2F2;">

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" style="background-color: #82B6D9!important;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'Posts_App:home' %}">XYZ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div>
                <a class="nav-link" href="{% url 'Posts_App:home' %}">Home</a>
            </div>
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    {% if user.profile.profile_pic %}
                    <a class="nav-link" href="{% url 'Login_App:userprofile' %}"><img
                            src="/media/{{user.profile.profile_pic}}" width="40px" height="40px" class="rounded-circle"></a>
                    {% else %}
                    <a class="nav-link" href="{% url 'Login_App:userprofile' %}"><img src="/media/default.jpg"
                                                                                      width="40px" height="40px"
                                                                                      class="rounded-circle"></a>
                    {% endif %}
                </li>
                <li>
                    <a class="nav-link " href="{% url 'Login_App:logout' %}"><i
                            class="fas fa-sign-out-alt"></i>Logout</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a href="{% url 'Login_App:login' %}" class="btn btn-outline-secondary">Login</a>
                    <a href="{% url 'Login_App:signup' %}" class="btn btn-secondary">SignUp</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container" style="padding-top:100px;">
    {% block body_block %} {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>

</body>
</html>